language: python
python:
 - "3.6"

before_install:
 - cd ServerSetup
 - docker-compose build
 - docker-compose up

install:
 - pip install -r testing/requirements.txt
script:
 - python testing/initial_test.py
 - locust -f testing/locustfile.py --host=http://grantxps.student.rit.edu:80
