language: python
python:
 - "3.6"
install:
 - pip install -r testing/requirements.txt
script:
 - python testing/initial_test.py
 - locust -f testing/locustfile.py --host=http://grantxps.student.rit.edu:80
